### ISSUE TITLE
docker_entrypoint.sh

### ISSUE THREAD

**Issue by fwt11** [emqx/emqx-rel#514]
in the latest docker_entrypoint.sh
```
if [[ -z "$EMQX_WAIT_TIME" ]]; then
    export EMQX_WAIT_TIME=5
fi

if [[ -z "$EMQX_NODE_NAME" ]]; then
    export EMQX_NODE_NAME="$EMQX_NAME@$EMQX_HOST"
fi
```
the second  '_' in the var name shoud be  '__'?   so these code should be
```
if [[ -z "$EMQX_WAIT__TIME" ]]; then
    export EMQX_WAIT__TIME=5
fi

if [[ -z "$EMQX_NODE__NAME" ]]; then
    export EMQX_NODE__NAME="$EMQX_NAME@$EMQX_HOST"
fi```

**Comment by vowstar** [comment]
Please don't do this. Not all variables satisfy this substitution rule.

This substitution rule is just to facilitate the correspondence between environment variables and erlang configuration, but these two environment variables are special, and their names are not converted when they are actually used.

``EMQX_WAIT_TIME`` is used in https://github.com/emqx/emqx-docker/blob/master/v3.1/start.sh#L17
This is a workaround to ensure emqx is running.

``$EMQX_NODE_NAME`` is used in https://github.com/emqx/emqx-rel/blob/master/bin/emqx#L205-L206 and https://github.com/emqx/emqx-rel/blob/master/bin/emqx_ctl#L40-L41 for setting erlang node name.

Please do not change these two, otherwise it will cause malfunction.

**Comment by zhanghongtong** [comment]
Hi, @vowstar 
You are right. Thank you for your reply

**Comment by fwt11** [comment]
so, there is no `$EMQX_NODE__NAME`  in the latest docker_entrypoint.sh? It seems that `node.name` in emqx.conf will not be set?

**Comment by zhanghongtong** [comment]
Yes, there is no `$EMQX_NODE__NAME` in the latest `docker_entrypoint.sh`, `$EMQX_NODE_NAME` will be put into `data/config/app.$date.conf` by magic method

**Comment by fwt11** [comment]
thank you very much!

**Comment by zhanghongtong** [comment]
You're welcome :)
